### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheKerbycz** [hypokondrickard/pyNIBE#1]
Hello, i tried to use this script, but it gave me this error:

```
Traceback (most recent call last):
  File "nibe.py", line 22, in <module>
    my_datapoint["measurement"] = "NIBE-1245-8"
NameError: name 'my_datapoint' is not defined
```

I'm linux and python beginner, so I don't know what is wrong. Can you please help me?
Thanks

**Comment by hypokondrickard** [comment]
Hi there

If you're using the influxdb example, it seems that your connection to nibe
uplink hasn't been properly established.

Try doing the following:

from pyNIBE import pyNIBE
my_heater = pyNIBE('<nibe uplink username>','<nibe uplink
password>','<system ID>')
my_heater.open()

print my_heater

my_heater.close()

**Comment by TheKerbycz** [comment]
Yes, I'm using the influxdb example.
The code output is:

```
root@kerby:~/# python nibe-print.py
<pyNIBE.pyNIBE.pyNIBE object at 0x7fa9f1b3f1d0>
```

But it is same even if I change password to nothing, so I think you are right.

**Comment by hypokondrickard** [comment]
make sure you've got the correct system ID. It's in the URL under service
info when logged into the uplink web ui. If you're comfortable with it you
could just set a temporary password and give me your credentials and I'll
give it a try?

/Rickard

**Comment by TheKerbycz** [comment]
Just checked and I have the correct ID.
Where can I send you the password? Or messege me with the new password and I will change it.
Thanks for you help

**Comment by hypokondrickard** [comment]
just set it to whatever and drop me an email with credentials and systemID. rickard@ostman.net.

**Comment by TheKerbycz** [comment]
Thank you for your support!
